name: fit_mart
description: App for buying and selling workout plans.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: "^0.5.0"
    # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
    # Add the dependencies for any other Firebase products you want to use in your app
    # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.0+1
  indexed_list_view: ^1.1.5
  cloud_firestore: ^0.14.0+2
  scroll_to_index: ^1.0.6
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+21
  better_player: ^0.0.36
  chewie: ^0.12.0
  video_player: ^1.0.1
  rxdart: ^0.24.1
  image_cropper: ^1.3.1
  circular_countdown_timer: ^0.0.8
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

