name: fit_mart
description: App for buying and selling workout plans.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: "^0.5.0"
    # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
    # Add the dependencies for any other Firebase products you want to use in your app
    # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.0+2"
  firebase_storage: "^4.0.0"

  cupertino_icons: ^0.1.3
  smooth_star_rating: ^1.1.1
  chewie: ^0.9.10
  video_player: ^0.10.12+4
  rxdart: ^0.24.1
  video_thumbnail: ^0.2.2
  item_selector: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

